CREATE TABLE CLIENT (
    ID_CLIENT NUMBER PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL,
    PRENOM VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    TELEPHONE VARCHAR2(15)
);

CREATE TABLE PRODUIT (
    ID_PRODUIT NUMBER PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    PRIX NUMBER(10,2) NOT NULL,
    STOCK NUMBER NOT NULL
);

CREATE TABLE COMMANDES (
    ID_COMMANDE NUMBER PRIMARY KEY,
    ID_CLIENT NUMBER NOT NULL,
    DATE_COMMANDE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

CREATE TABLE DETAIL_COMMANDE (
    ID_COMMANDE NUMBER,
    ID_PRODUIT NUMBER,
    QUANTITE NUMBER NOT NULL,
    PRIMARY KEY (ID_COMMANDE, ID_PRODUIT),
    CONSTRAINT FK_COMMANDE FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDES(ID_COMMANDE),
    CONSTRAINT FK_PRODUIT FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT)
);

-- Ajouter la colonne Catégorie à la table PRODUIT
ALTER TABLE PRODUIT ADD CATEGORIE VARCHAR2(20);

-- Ajouter la colonne Date de commande à la table COMMANDES avec SYSDATE par défaut
ALTER TABLE COMMANDES ADD DATE_COMMANDE DATE DEFAULT SYSDATE;
